"""Built-in demo security policy document for coverage mapping demonstration.

A realistic ~20-paragraph security policy spanning access control, encryption,
monitoring, asset management, HR security, supplier security, and incident response.
Some controls are clearly referenced (-> COVERED), others vaguely (-> PARTIAL),
and some are entirely missing (-> GAP).
"""

DEMO_POLICY_TEXT = """
## Access Control Policy

Access Control Requirement: All access to information systems shall be authorised,
reviewed, and revoked when no longer required. This aligns with ISO 27001 A.5.15.

Multi-factor authentication shall be enforced for all remote access to corporate
resources and for all privileged accounts. This control is referenced in CIS V8
safeguard 6.3.

Privileged access rights shall be formally requested, approved through the ticketing
system, provisioned with the principle of least privilege, and reviewed on a quarterly
basis by the asset owner. Access rights must be removed within 24 hours of an employee
or contractor leaving the organisation.

## Endpoint Protection

All endpoint devices including laptops, desktops, and servers shall be equipped with
anti-malware software, a host-based firewall, and full-disk encryption. These
protections shall be enforced via Group Policy and monitored by the central endpoint
management platform.

Mobile devices that access, store, or process corporate data must be enrolled in a
Mobile Device Management (MDM) platform. The MDM shall enforce minimum OS version,
screen lock, and remote wipe capability.

## Network Security

The corporate network shall be segmented into production, staging, development, and
guest environments. Firewall rules between segments shall follow least-privilege
principles and shall be reviewed at least quarterly to identify and remove unused or
overly permissive rules.

No production system shall expose administrative interfaces (SSH, RDP, management
consoles) directly to the public internet. Administrative access shall require a
VPN or a privileged access workstation (PAW).

## Cloud Security

All cloud environments (AWS, Azure, GCP) shall be configured in accordance with
CIS hardening benchmarks. Cloud security posture shall be continuously monitored
through the Cloud Security Posture Management (CSPM) tool.

All cloud data stores — including S3 buckets, Azure Blob Storage, and managed
database services — shall have encryption-at-rest enabled. Where supported,
customer-managed encryption keys shall be used.

## Vulnerability Management

Automated vulnerability scanning shall be performed across all internal and external
network assets on a weekly basis. Scan results shall be reviewed by the vulnerability
management team and critical findings shall be escalated within 24 hours.

Security patches shall be applied within the following SLAs: critical severity within
7 calendar days, high severity within 14 calendar days, medium severity within 30
calendar days. Emergency patches for actively exploited vulnerabilities shall be
deployed within 48 hours.

## Security Monitoring

A Security Information and Event Management (SIEM) platform shall collect and
correlate security events from all critical assets on a 24/7 basis. Log sources
shall include firewalls, endpoints, authentication systems, cloud platforms, and
critical applications.

Security alerts generated by the SIEM shall be triaged within 30 minutes and
assigned to a qualified security analyst for investigation.

## Incident Response

The organisation shall maintain and regularly update an incident response plan.
The plan shall define roles, responsibilities, communication procedures, and
escalation paths. The plan shall be tested at least annually through tabletop
exercises or simulated incidents.

## Human Resources Security

Background verification checks shall be carried out on all candidates for
employment in accordance with applicable laws and regulations. The scope of
checks shall be proportional to the sensitivity of the role.

All employees and contractors shall sign a confidentiality or non-disclosure
agreement as a condition of employment. These agreements shall be reviewed
annually to ensure they remain fit for purpose.

## Supplier Security

Third-party suppliers shall be assessed for security risk prior to engagement
and on an ongoing basis. The assessment shall consider the type of data accessed,
the criticality of the service, and the supplier's own security posture.

## Business Continuity

Business continuity and disaster recovery plans shall be maintained for all
business-critical systems. Plans shall be reviewed and tested at least annually,
with lessons learned incorporated into plan updates.

## Data Protection

Measures shall be in place to prevent unauthorised disclosure or exfiltration of
sensitive data. Data classification labels shall be applied to all information
assets, and data handling procedures shall be enforced in accordance with the
classification level.

Data at rest shall be encrypted using AES-256 or equivalent. Data in transit
shall be encrypted using TLS 1.2 or higher. Cryptographic key material shall be
managed through an enterprise key management service with access logging enabled.

## Software Development

All software development shall follow a secure development lifecycle. Code shall
undergo peer review, static analysis, and security testing prior to deployment.
Production deployments shall be performed through automated CI/CD pipelines with
separation of duties between development and deployment roles.

## Policy Governance

This information security policy shall be reviewed and approved by the Chief
Information Security Officer (CISO) on an annual basis. Policy exceptions shall
be formally documented, risk-assessed, and approved with an expiry date not
exceeding 12 months.
"""


def get_demo_policy_text() -> str:
    """Return the built-in demo policy text."""
    return DEMO_POLICY_TEXT.strip()
